"use strict";
/* PWA, responsive navigation, persistence and install layer — v4.0.0 */
const ADVAR_VERSION="4.0.0";
const PWA_TEXT={
 en:{family:"Persian Music Scales · Historical Theory Series",eyebrow:"A scholarly interactive edition",lead:"Explore exact fret divisions, historical interval theory, listening models, geometrical construction, and modal structures.",start:"Start guided lesson",open:"Open Atlas",continue:"Continue previous session",sources:"About the sources",dismissWelcome:"Do not show this opening next time",learn:"Learn",explore:"Explore",construct:"Construct",listen:"Listen",more:"More",modes:"Species & Modes",training:"Training & Data",instrument:"Instrument view",about:"About",settings:"Settings",install:"Install app",scales:"Persian Music Scales",showInstrument:"Show illustrative instrument",hideInstrument:"Hide illustrative instrument",zoomOut:"Zoom out",zoomIn:"Zoom in",play:"Play",settingsTitle:"Settings",settingWelcome:"Show opening screen on launch",settingContrast:"High contrast",settingText:"Larger text",settingMotion:"Reduce motion",reset:"Reset learning progress",aboutTitle:"About the Atlas",aboutSeries:"Persian Music Scales · Historical Theory Series",aboutSummary:"A multilingual digital-humanities application for exploring exact string divisions, interval structures, listening models, and modal categories.",creator:"Creator and developer",creatorCopy:"Scientist, independent developer, and creator of Persian Music Scales.",links:"Project links",close:"Close",installTitle:"Install Advar Atlas",installHelp:"Use your browser menu and choose “Install app” or “Add to Home Screen”.",offline:"You are offline. The cached Atlas remains available.",online:"Connection restored.",update:"A new version is available.",updateButton:"Update",resetConfirm:"Reset all saved lesson progress and settings?"},
 fa:{family:"مقیاس‌های موسیقی ایرانی · مجموعهٔ نظریهٔ تاریخی",eyebrow:"ویرایش تعاملی پژوهشی",lead:"تقسیمات دقیق دستان‌ها، نظریهٔ تاریخی فواصل، مدل‌های شنیداری، ساخت هندسی و ساختارهای مقامی را کاوش کنید.",start:"شروع درس هدایت‌شده",open:"گشودن اطلس",continue:"ادامهٔ نشست پیشین",sources:"دربارهٔ منابع",dismissWelcome:"این صفحه در اجرای بعدی نمایش داده نشود",learn:"آموزش",explore:"کاوش",construct:"ساخت",listen:"شنیدن",more:"بیشتر",modes:"اجناس و ادوار",training:"تمرین و داده",instrument:"نمای ساز",about:"درباره",settings:"تنظیمات",install:"نصب برنامه",scales:"مقیاس‌های موسیقی ایرانی",showInstrument:"نمایش ساز تصویری",hideInstrument:"پنهان‌کردن ساز تصویری",zoomOut:"کوچک‌نمایی",zoomIn:"بزرگ‌نمایی",play:"پخش",settingsTitle:"تنظیمات",settingWelcome:"نمایش صفحهٔ آغاز در اجرای برنامه",settingContrast:"کنتراست زیاد",settingText:"متن بزرگ‌تر",settingMotion:"کاهش حرکت",reset:"پاک‌کردن پیشرفت آموزشی",aboutTitle:"دربارهٔ اطلس",aboutSeries:"مقیاس‌های موسیقی ایرانی · مجموعهٔ نظریهٔ تاریخی",aboutSummary:"برنامه‌ای چندزبانه در حوزهٔ علوم انسانی دیجیتال برای بررسی تقسیمات دقیق سیم، ساختار فواصل، مدل‌های شنیداری و مقوله‌های مقامی.",creator:"طراح و توسعه‌دهنده",creatorCopy:"محقق، توسعه‌دهندهٔ مستقل و خالق پروژهٔ مقیاس‌های موسیقی ایرانی.",links:"پیوندهای پروژه",close:"بستن",installTitle:"نصب اطلس ادوار",installHelp:"منوی مرورگر را باز کنید و «Install app» یا «Add to Home Screen» را انتخاب کنید.",offline:"اتصال اینترنت قطع است؛ نسخهٔ ذخیره‌شدهٔ اطلس در دسترس است.",online:"اتصال اینترنت برقرار شد.",update:"نسخهٔ تازه‌ای در دسترس است.",updateButton:"به‌روزرسانی",resetConfirm:"همهٔ پیشرفت‌ها و تنظیمات ذخیره‌شده پاک شوند؟"},
 ar:{family:"مقامات الموسيقى الفارسية · سلسلة النظرية التاريخية",eyebrow:"نسخة علمية تفاعلية",lead:"استكشف تقسيمات الدساتين الدقيقة ونظرية الفواصل التاريخية والنماذج السمعية والبناء الهندسي والبنى المقامية.",start:"ابدأ الدرس الموجّه",open:"افتح الأطلس",continue:"تابع الجلسة السابقة",sources:"حول المصادر",dismissWelcome:"لا تعرض شاشة البداية في المرة القادمة",learn:"التعلّم",explore:"الاستكشاف",construct:"البناء",listen:"الاستماع",more:"المزيد",modes:"الأجناس والأدوار",training:"التدريب والبيانات",instrument:"عرض الآلة",about:"حول",settings:"الإعدادات",install:"تثبيت التطبيق",scales:"مقامات الموسيقى الفارسية",showInstrument:"إظهار الآلة التوضيحية",hideInstrument:"إخفاء الآلة التوضيحية",zoomOut:"تصغير",zoomIn:"تكبير",play:"تشغيل",settingsTitle:"الإعدادات",settingWelcome:"إظهار شاشة البداية عند التشغيل",settingContrast:"تباين عالٍ",settingText:"نص أكبر",settingMotion:"تقليل الحركة",reset:"إعادة ضبط التقدم",aboutTitle:"حول الأطلس",aboutSeries:"مقامات الموسيقى الفارسية · سلسلة النظرية التاريخية",aboutSummary:"تطبيق متعدد اللغات في العلوم الإنسانية الرقمية لدراسة تقسيمات الوتر الدقيقة وبنى الفواصل والنماذج السمعية والفئات المقامية.",creator:"المنشئ والمطوّر",creatorCopy:"عالم ومطوّر مستقل ومنشئ مشروع مقامات الموسيقى الفارسية.",links:"روابط المشروع",close:"إغلاق",installTitle:"تثبيت أطلس الأدوار",installHelp:"افتح قائمة المتصفح واختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».",offline:"أنت غير متصل؛ النسخة المخزنة من الأطلس ما زالت متاحة.",online:"تمت استعادة الاتصال.",update:"يتوفر إصدار جديد.",updateButton:"تحديث",resetConfirm:"هل تريد مسح كل التقدم والإعدادات المحفوظة؟"},
 tr:{family:"Persian Music Scales · Tarihsel Kuram Dizisi",eyebrow:"Bilimsel etkileşimli sürüm",lead:"Kesin perde bölümlerini, tarihsel aralık kuramını, dinleme modellerini, geometrik kuruluşu ve makam yapılarını keşfedin.",start:"Yönlendirilmiş derse başla",open:"Atlası aç",continue:"Önceki oturuma devam et",sources:"Kaynaklar hakkında",dismissWelcome:"Bu açılışı bir daha gösterme",learn:"Öğren",explore:"Keşfet",construct:"Kur",listen:"Dinle",more:"Daha",modes:"Cinsler ve Devirler",training:"Alıştırma ve Veri",instrument:"Çalgı görünümü",about:"Hakkında",settings:"Ayarlar",install:"Uygulamayı yükle",scales:"Persian Music Scales",showInstrument:"Açıklayıcı çalgıyı göster",hideInstrument:"Açıklayıcı çalgıyı gizle",zoomOut:"Uzaklaştır",zoomIn:"Yakınlaştır",play:"Çal",settingsTitle:"Ayarlar",settingWelcome:"Başlangıç ekranını açılışta göster",settingContrast:"Yüksek kontrast",settingText:"Daha büyük metin",settingMotion:"Hareketi azalt",reset:"Öğrenme ilerlemesini sıfırla",aboutTitle:"Atlas hakkında",aboutSeries:"Persian Music Scales · Tarihsel Kuram Dizisi",aboutSummary:"Kesin tel bölümlerini, aralık yapılarını, dinleme modellerini ve makamsal kategorileri incelemek için çok dilli bir dijital beşerî bilimler uygulaması.",creator:"Yaratıcı ve geliştirici",creatorCopy:"Bilim insanı, bağımsız geliştirici ve Persian Music Scales projesinin yaratıcısı.",links:"Proje bağlantıları",close:"Kapat",installTitle:"Advar Atlası yükle",installHelp:"Tarayıcı menüsünü açın ve “Uygulamayı yükle” veya “Ana Ekrana Ekle” seçeneğini seçin.",offline:"Çevrimdışısınız; önbelleğe alınan Atlas kullanılabilir.",online:"Bağlantı yeniden kuruldu.",update:"Yeni bir sürüm kullanılabilir.",updateButton:"Güncelle",resetConfirm:"Kaydedilmiş tüm ders ilerlemesi ve ayarlar sıfırlansın mı?"}
};
const pwaText=(key)=>((PWA_TEXT[typeof uiLanguage!=="undefined"?uiLanguage:"en"]||PWA_TEXT.en)[key]||PWA_TEXT.en[key]||key);
const qs=(s,root=document)=>root.querySelector(s),qsa=(s,root=document)=>[...root.querySelectorAll(s)];
const stateKey="urmawiAdvarPwaStateV4";let deferredInstallPrompt=null;let pendingWorker=null;let suppressMobilePanelScroll=true;let completedLessons=new Set();let mobileTheoryWidth=1050;let pitchBarTimer=null;
function readState(){try{return JSON.parse(localStorage.getItem(stateKey)||"{}")||{}}catch(_){return {}}}
function writeState(patch={}){const next={...readState(),...patch,version:ADVAR_VERSION,updatedAt:Date.now()};try{localStorage.setItem(stateKey,JSON.stringify(next))}catch(_){}return next}
function isPhone(){return matchMedia("(max-width:700px)").matches}
function isEmbed(){return new URLSearchParams(location.search).get("embed")==="1"||window.self!==window.top}
function setText(id,key){const el=$(id);if(el)el.textContent=pwaText(key)}
function applyPwaLanguage(){
 const eyebrow=qs(".eyebrow");if(eyebrow){eyebrow.innerHTML=`<a class="family-link" href="https://persianmusicscales.github.io/Persian-Music-Scales-App/" target="_blank" rel="noopener">${pwaText("scales")}</a><span> · ${pwaText("family").split(" · ").slice(1).join(" · ")||"Historical Theory Series"}</span>`}
 setText("welcomeFamily","family");setText("welcomeEyebrow","eyebrow");setText("welcomeLead","lead");setText("welcomeStart","start");setText("welcomeAtlas","open");setText("welcomeContinue","continue");setText("welcomeSources","sources");setText("welcomeDismiss","dismissWelcome");
 setText("mobileLearn","learn");setText("mobileExplore","explore");setText("mobileConstruct","construct");setText("mobileListen","listen");setText("mobileMore","more");setText("moreSheetTitle","more");setText("moreModes","modes");setText("moreTraining","training");setText("moreInstrument","instrument");setText("moreSources","sources");setText("moreAbout","about");setText("moreSettings","settings");setText("moreInstall","install");setText("moreScales","scales");
 setText("settingsTitle","settingsTitle");setText("settingWelcomeLabel","settingWelcome");setText("settingContrastLabel","settingContrast");setText("settingTextLabel","settingText");setText("settingMotionLabel","settingMotion");setText("resetProgressBtn","reset");
 setText("aboutDialogTitle","aboutTitle");setText("aboutSeries","aboutSeries");setText("aboutSummary","aboutSummary");setText("aboutCreatorTitle","creator");setText("aboutCreatorCopy","creatorCopy");setText("aboutLinksTitle","links");setText("closeAboutDialog","close");
 setText("installHelpTitle","installTitle");setText("installHelpCopy","installHelp");setText("closeInstallHelp","close");setText("installAppBtn","install");setText("updateToastText","update");setText("updateAppBtn","updateButton");
 const toggle=$("mobileInstrumentToggle");if(toggle)toggle.textContent=document.body.classList.contains("mobile-instrument-open")?pwaText("hideInstrument"):pwaText("showInstrument");if($("mobileZoomOut"))$("mobileZoomOut").setAttribute("aria-label",pwaText("zoomOut"));if($("mobileZoomIn"))$("mobileZoomIn").setAttribute("aria-label",pwaText("zoomIn"));if($("mobilePitchPlay"))$("mobilePitchPlay").textContent=`▶ ${pwaText("play")}`;
}
function showWelcome(mode="default"){$("welcomeScreen")?.classList.remove("hidden");if(mode==="continue")$("welcomeContinue")?.removeAttribute("hidden")}
function hideWelcome(){$("welcomeScreen")?.classList.add("hidden")}
function openDialog(id){$(id)?.classList.add("open")}
function closeDialog(id){$(id)?.classList.remove("open")}
function openSheet(id){qsa(".app-sheet.open").forEach(x=>x.classList.remove("open"));const el=$(id);if(el){el.classList.add("open");el.setAttribute("aria-hidden","false")}}
function closeSheets(){qsa(".app-sheet.open").forEach(el=>{el.classList.remove("open");el.setAttribute("aria-hidden","true")})}
function syncMobileNav(){qsa("[data-mobile-panel]").forEach(b=>b.classList.toggle("active",b.dataset.mobilePanel===activePanel));$("mobileMoreBtn")?.classList.toggle("active",["modes","train"].includes(activePanel))}
function centerSelectedFret(behavior="smooth"){
 if(!isPhone())return;const shell=$("monoScrollShell");if(!shell)return;const target=xFor(NOTES[selected])*(mobileTheoryWidth/1244)-shell.clientWidth/2;shell.scrollTo({left:Math.max(0,target),behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"auto":behavior})
}
function restoreState(){
 const st=readState();completedLessons=new Set(Array.isArray(st.completedLessons)?st.completedLessons:[]);mobileTheoryWidth=Math.max(800,Math.min(1600,Number(st.mobileTheoryWidth)||1050));document.documentElement.style.setProperty("--mobile-theory-width",`${mobileTheoryWidth}px`);if($("mobileZoomLabel"))$("mobileZoomLabel").textContent=`${Math.round(mobileTheoryWidth/10.5)}%`;if(Number.isInteger(st.scoreCorrect))scoreCorrect=st.scoreCorrect;if(Number.isInteger(st.scoreTotal))scoreTotal=st.scoreTotal;updateScore();
 if(Number.isInteger(st.selected))selected=Math.max(0,Math.min(NOTES.length-1,st.selected));
 if(Number.isInteger(st.lessonIndex))lessonIndex=Math.max(0,Math.min(LESSONS.length-1,st.lessonIndex));
 if(Number.isInteger(st.constructionStep))constructionStep=Math.max(0,Math.min(CONSTRUCTION.length-1,st.constructionStep));
 const values={baseFrequency:st.baseFrequency,stringLength:st.stringLength,waveform:st.waveform,audioMode:st.audioMode,masterVolume:st.masterVolume,pluckDecay:st.pluckDecay};Object.entries(values).forEach(([id,v])=>{if(v!==undefined&&$(id))$(id).value=v});
 document.body.classList.toggle("high-contrast",!!st.highContrast);document.body.classList.toggle("large-text",!!st.largeText);document.body.classList.toggle("reduce-motion",!!st.reduceMotion);
 const requestedPanel=new URLSearchParams(location.search).get("panel");const panel=requestedPanel||st.activePanel||"learn";activatePanel(["learn","explore","construct","listen","modes","train"].includes(panel)?panel:"learn");
 if(!new URLSearchParams(location.search).has("view")&&Number.isInteger(st.viewMode))applyViewMode(st.viewMode);
 renderLessons();renderMonochord();updateExplore();syncMobileNav();setTimeout(centerSelectedFret,60)
}
function saveCurrent(){writeState({activePanel,selected,lessonIndex,constructionStep,viewMode,completedLessons:[...completedLessons],mobileTheoryWidth,scoreCorrect,scoreTotal,baseFrequency:$("baseFrequency")?.value,stringLength:$("stringLength")?.value,waveform:$("waveform")?.value,audioMode:$("audioMode")?.value,masterVolume:$("masterVolume")?.value,pluckDecay:$("pluckDecay")?.value,highContrast:document.body.classList.contains("high-contrast"),largeText:document.body.classList.contains("large-text"),reduceMotion:document.body.classList.contains("reduce-motion")})}
function hookStateFunctions(){
 const oldActivate=activatePanel;activatePanel=function(name){oldActivate(name);syncMobileNav();saveCurrent();if(isPhone()&&!suppressMobilePanelScroll)scrollTo({top:$("monoPanel")?.offsetTop||0,behavior:"smooth"})};
 const oldSelect=selectNote;selectNote=function(index,play=false){oldSelect(index,play);saveCurrent();updateMobilePitchBar();setTimeout(centerSelectedFret,20)};
 const oldLesson=setLesson;setLesson=function(i){oldLesson(i);decorateLessons();saveCurrent()};
 const oldConstruction=setConstruction;setConstruction=function(i){oldConstruction(i);saveCurrent()};
 const oldView=applyViewMode;applyViewMode=function(mode=viewMode){oldView(mode);saveCurrent()};
 const oldLanguage=applyStaticLanguage;applyStaticLanguage=function(){oldLanguage();applyPwaLanguage()};
 const oldRender=renderMonochord;renderMonochord=function(){oldRender();attachLongPress()};const oldLessons=renderLessons;renderLessons=function(){oldLessons();decorateLessons()};const oldAnswer=answerQuiz;answerQuiz=function(button,value){oldAnswer(button,value);saveCurrent()};
}

function decorateLessons(){qsa(".lesson-btn").forEach((b,i)=>{b.classList.toggle("completed",completedLessons.has(i));b.setAttribute("aria-label",`${i+1}. ${b.textContent.trim()}${completedLessons.has(i)?" ✓":""}`)})}
function markLessonComplete(i){completedLessons.add(Math.max(0,Math.min(LESSONS.length-1,i)));decorateLessons();saveCurrent()}
function changeTheoryZoom(delta){mobileTheoryWidth=Math.max(800,Math.min(1600,mobileTheoryWidth+delta));document.documentElement.style.setProperty("--mobile-theory-width",`${mobileTheoryWidth}px`);if($("mobileZoomLabel"))$("mobileZoomLabel").textContent=`${Math.round(mobileTheoryWidth/10.5)}%`;saveCurrent();setTimeout(()=>centerSelectedFret("auto"),20)}
function updateMobilePitchBar(){if(!isPhone())return;const n=NOTES[selected],bar=$("mobilePitchBar");if(!bar)return;$("mobilePitchNote").textContent=n.label;$("mobilePitchDetails").textContent=`${n.lenD}/${n.lenN} · ${fixed(cents(n))}¢ · ${fixed(currentBase()*frequencyRatio(n),1)} Hz`;bar.hidden=false;clearTimeout(pitchBarTimer);pitchBarTimer=setTimeout(()=>bar.hidden=true,4200)}
function attachLongPress(){qsa("#fretLayer .fret").forEach((el,i)=>{if(el.dataset.longpress)return;el.dataset.longpress="1";let timer=null;const clear=()=>{if(timer){clearTimeout(timer);timer=null}};el.addEventListener("pointerdown",()=>{timer=setTimeout(()=>{tone(i);navigator.vibrate?.(18)},420)},{passive:true});el.addEventListener("pointerup",clear,{passive:true});el.addEventListener("pointercancel",clear,{passive:true});el.addEventListener("pointerleave",clear,{passive:true})})}
function setupSwipeLessons(){const el=$("panel-learn");if(!el)return;let x0=0,y0=0;el.addEventListener("pointerdown",e=>{x0=e.clientX;y0=e.clientY},{passive:true});el.addEventListener("pointerup",e=>{const dx=e.clientX-x0,dy=e.clientY-y0;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.4)setLesson(lessonIndex+(dx<0?1:-1))},{passive:true})}
function toggleInstrument(){const on=document.body.classList.toggle("mobile-instrument-open");$("mobileInstrumentToggle")?.setAttribute("aria-expanded",String(on));applyPwaLanguage();if(on)setTimeout(()=>$("instrumentSvg")?.scrollIntoView({behavior:"smooth",block:"center"}),80)}
function syncSettings(){const st=readState();$("settingWelcome").checked=st.showWelcome!==false;$("settingContrast").checked=document.body.classList.contains("high-contrast");$("settingText").checked=document.body.classList.contains("large-text");$("settingMotion").checked=document.body.classList.contains("reduce-motion")}
function requestInstall(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null;updateInstallButtons()})}else openDialog("installHelpDialog")}
function updateInstallButtons(){const installed=matchMedia("(display-mode:standalone)").matches||navigator.standalone;const visible=!installed&&(!!deferredInstallPrompt||/iphone|ipad|ipod/i.test(navigator.userAgent));["installAppBtn","moreInstallBtn"].forEach(id=>{const el=$(id);if(el)el.hidden=!visible})}
function announceNetwork(online){const el=$("networkBanner");if(!el)return;el.textContent=online?pwaText("online"):pwaText("offline");el.classList.add("show");setTimeout(()=>el.classList.remove("show"),online?2600:4600)}
function registerServiceWorker(){if(!("serviceWorker" in navigator)||!/^https?:$/.test(location.protocol))return;navigator.serviceWorker.register("./service-worker.js").then(reg=>{reg.addEventListener("updatefound",()=>{const w=reg.installing;if(!w)return;w.addEventListener("statechange",()=>{if(w.state==="installed"&&navigator.serviceWorker.controller){pendingWorker=w;$("updateToast").hidden=false}})})}).catch(console.warn);navigator.serviceWorker.addEventListener("controllerchange",()=>location.reload())}
function setupWelcome(){const st=readState(),params=new URLSearchParams(location.search);const skip=params.get("welcome")==="0"||params.get("skipWelcome")==="1"||isEmbed();if(skip||st.showWelcome===false)hideWelcome();else showWelcome(Object.keys(st).length?"continue":"default");$("welcomeContinue").hidden=!st.activePanel}
function initializePwa(){
 document.body.classList.toggle("embed-mode",isEmbed());hookStateFunctions();restoreState();applyPwaLanguage();attachLongPress();setupSwipeLessons();setupWelcome();syncSettings();updateInstallButtons();registerServiceWorker();
 $("welcomeStart")?.addEventListener("click",()=>{activatePanel("learn");setLesson(0);hideWelcome();writeState({showWelcome:true})});$("welcomeAtlas")?.addEventListener("click",()=>{activatePanel("explore");hideWelcome();writeState({showWelcome:true})});$("welcomeContinue")?.addEventListener("click",hideWelcome);$("welcomeSources")?.addEventListener("click",()=>{hideWelcome();openSourceDialog()});$("welcomeDismiss")?.addEventListener("click",()=>{writeState({showWelcome:false});hideWelcome()});
 qsa("[data-mobile-panel]").forEach(b=>b.addEventListener("click",()=>activatePanel(b.dataset.mobilePanel)));$("mobileMoreBtn")?.addEventListener("click",()=>openSheet("mobileMoreSheet"));$("mobileHeaderMenuBtn")?.addEventListener("click",()=>openSheet("mobileMoreSheet"));qsa("[data-more-panel]").forEach(b=>b.addEventListener("click",()=>{activatePanel(b.dataset.morePanel);closeSheets()}));qsa("[data-close-sheet]").forEach(b=>b.addEventListener("click",closeSheets));
 $("mobileInstrumentToggle")?.addEventListener("click",toggleInstrument);$("mobileZoomOut")?.addEventListener("click",()=>changeTheoryZoom(-125));$("mobileZoomIn")?.addEventListener("click",()=>changeTheoryZoom(125));$("mobilePitchPlay")?.addEventListener("click",()=>tone(selected));$("moreInstrumentBtn")?.addEventListener("click",()=>{closeSheets();if(isPhone())toggleInstrument();else applyViewMode(2)});$("moreSourcesBtn")?.addEventListener("click",()=>{closeSheets();openSourceDialog()});$("moreAboutBtn")?.addEventListener("click",()=>{closeSheets();openDialog("aboutDialog")});$("moreSettingsBtn")?.addEventListener("click",()=>{closeSheets();syncSettings();openSheet("settingsSheet")});
 $("closeAboutDialog")?.addEventListener("click",()=>closeDialog("aboutDialog"));$("aboutDialog")?.addEventListener("click",e=>{if(e.target===$("aboutDialog"))closeDialog("aboutDialog")});$("closeInstallHelp")?.addEventListener("click",()=>closeDialog("installHelpDialog"));$("installHelpDialog")?.addEventListener("click",e=>{if(e.target===$("installHelpDialog"))closeDialog("installHelpDialog")});
 $("installAppBtn")?.addEventListener("click",requestInstall);$("moreInstallBtn")?.addEventListener("click",()=>{closeSheets();requestInstall()});
 $("lessonDemonstrate")?.addEventListener("click",()=>markLessonComplete(lessonIndex),{capture:true});$("lessonNext")?.addEventListener("click",()=>markLessonComplete(lessonIndex),{capture:true});
 $("settingWelcome")?.addEventListener("change",e=>writeState({showWelcome:e.target.checked}));$("settingContrast")?.addEventListener("change",e=>{document.body.classList.toggle("high-contrast",e.target.checked);saveCurrent()});$("settingText")?.addEventListener("change",e=>{document.body.classList.toggle("large-text",e.target.checked);saveCurrent()});$("settingMotion")?.addEventListener("change",e=>{document.body.classList.toggle("reduce-motion",e.target.checked);saveCurrent()});$("resetProgressBtn")?.addEventListener("click",()=>{if(confirm(pwaText("resetConfirm"))){localStorage.removeItem(stateKey);location.reload()}});
 ["baseFrequency","stringLength","waveform","audioMode","masterVolume","pluckDecay"].forEach(id=>$(id)?.addEventListener("change",saveCurrent));$("languageSelect")?.addEventListener("change",()=>setTimeout(applyPwaLanguage,0));
 $("updateAppBtn")?.addEventListener("click",()=>pendingWorker?.postMessage({type:"SKIP_WAITING"}));$("dismissUpdateBtn")?.addEventListener("click",()=>$("updateToast").hidden=true);
 window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallButtons()});window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;updateInstallButtons();writeState({installed:true})});window.addEventListener("online",()=>announceNetwork(true));window.addEventListener("offline",()=>announceNetwork(false));window.addEventListener("resize",()=>{if(!isPhone())document.body.classList.remove("mobile-instrument-open");setTimeout(centerSelectedFret,50)});
 if(!navigator.onLine)announceNetwork(false);setTimeout(()=>{suppressMobilePanelScroll=false;centerSelectedFret("auto")},180);$("appVersion").textContent=ADVAR_VERSION;
}
initializePwa();
